name: Checkstyle

on:
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install -DskipTests --no-transfer-progress

      - name: Run Checkstyle
        run: mvn checkstyle:check
